from pathlib import Path
import re

Import("env")


PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
VERSION_FILE = PROJECT_DIR / "VERSION"
HEADER_FILE = PROJECT_DIR / "include" / "czone_firmware_version.h"


version = VERSION_FILE.read_text(encoding="utf-8").strip()
if not re.fullmatch(r"\d+\.\d+\.\d+", version):
    raise ValueError(f"VERSION must be semantic version X.Y.Z, got {version!r}")

content = (
    "#pragma once\n\n"
    "/* Generated by scripts/generate_version_header.py. Do not edit. */\n"
    f"#define CZONE_FIRMWARE_VERSION \"{version}\"\n"
)

HEADER_FILE.parent.mkdir(parents=True, exist_ok=True)
if not HEADER_FILE.exists() or HEADER_FILE.read_text(encoding="utf-8") != content:
    HEADER_FILE.write_text(content, encoding="utf-8")

print(f"CZone firmware version: {version}")
